image: Visual Studio 2019

init:
 - appveyor version
 - echo %APPVEYOR_BUILD_WORKER_IMAGE%
 - echo %APPVEYOR_BUILD_WORKER_CLOUD%


test_script:
- ps: $ErrorActionPreference = "Stop"
- ps: $expected_yarn_version = '1.22.19'
- ps: $actual_yarn_version = (yarn --version)
- ps: 'if($actual_yarn_version -ne $expected_yarn_version) { throw "Yarn version: $actual_yarn_version, expected: $expected_yarn_version"; }'
- ps: yarn add vue2-perfect-scrollbar
- ps: yarn install

build: off
