image: Visual Studio 2019

init:
 - appveyor version
 - echo %APPVEYOR_BUILD_WORKER_IMAGE%
 - echo %APPVEYOR_BUILD_WORKER_CLOUD%

install:
 # - pwsh: >-
 #      npm i -g corepack@0.18.0
      
 #      corepack prepare yarn@3.3.0 --activate
 #- ps: .\install_yarn.ps1
 -ps: npm install --global yarn


test_script:
- ps: $ErrorActionPreference = "Stop"
- ps: $expected_yarn_version = '1.22.22'
- ps: $actual_yarn_version = (yarn --version)
- ps: 'if($actual_yarn_version -ne $expected_yarn_version) { throw "Yarn version: $actual_yarn_version, expected: $expected_yarn_version"; }'
- ps: yarn add vue2-perfect-scrollbar
- ps: yarn install

build: off
